### ISSUE TITLE
Any plans on updating this?

### ISSUE THREAD

**Issue by ErCollao** [gnapse/incomplete_date#1]
Hi! I was about to code this functionality for a pet-project of mine, and decided to check for plugins that solve it... and this one seems to! But it's in an old format and seems unmaintained. Any chance it will get updated? Or should I take a stab at it?

**Comment by gnapse** [comment]
Hmmm, I do not think I have the bandwidth to do it myself right now, but I'd be willing to make the time to review and accept your contribution, and even help a bit if needed.

**Comment by ErCollao** [comment]
Thanks @gnapse ! I'll take a look at it in the weekend, and let you know if I need help

**Comment by gnapse** [comment]
Closed in #2 by @ErCollao
